import React, { useRef } from 'react';
import { Container, Row, Col, Button } from 'react-bootstrap';
import { ArrowRight } from 'lucide-react';
import { Link } from 'react-router-dom';
import TopNav from '../components/TopNav';
import Footer from '../components/Footer';

const Homepage: React.FC = () => {
  const aboutRef = useRef<HTMLDivElement>(null);
  const roadmapRef = useRef<HTMLDivElement>(null);

  const scrollToSection = (ref: React.RefObject<HTMLDivElement>) => {
    ref.current?.scrollIntoView({ behavior: 'smooth' });
  };

  const scrollToAbout = () => {
    scrollToSection(aboutRef);
  };

  const scrollToRoadmap = () => {
    scrollToSection(roadmapRef);
  };

  const teamRef = useRef<HTMLDivElement>(null);
  const partnersRef = useRef<HTMLDivElement>(null);

  const scrollToTeam = () => {
    scrollToSection(teamRef);
  };

  const scrollToPartners = () => {
    scrollToSection(partnersRef);
  };

  const roadmapPhases = [
    {
      phase: 1,
      title: "Inception",
      status: "COMPLETED",
      statusColor: "#16A34A",
      icon: "✓",
      description: [
        "Form the Lomen Club team by identifying core team members and recruiting volunteers from the Lomen community who are passionate about the project. 🤝",
        "Launch the Lomen Club website that showcases Lomen NFTs, details Lomen Club and its goals, and allows community members to connect and collaborate. 🌐",
        "Create social media accounts for Lomen Club on Twitter, Telegram, and other relevant platforms. Use these channels to share updates, engage with the community, and promote Lomen Club initiatives. 📱"
      ]
    },
    {
      phase: 2,
      title: "KCC Validator",
      status: "COMPLETED",
      statusColor: "#16A34A",
      icon: "✓",
      description: [
        "Apply for the KCC Validators Election to become a validator on the KCC network. This will enable Lomen Club to earn staking rewards and generate income through the validator's commission. 🔍",
        "Deploy the Lomen Club KCC Validator, and promote it to get votes from the community. 🚀",
        "Start getting initial funding from the 1% commission generated by the validator, which will be used to fund initial initiatives and projects. 💰"
      ]
    },
    {
      phase: 3,
      title: "Vault",
      status: "FUTURE",
      statusColor: "#6B7280",
      icon: "3",
      description: [
        "Create a vault to hold assets gained from the commission generated by the validator and the marketplace. 🔒",
        "Start generating staking rewards for Lomen holders through the vault, and begin distributing the rewards to Lomen holders on a regular basis. 💰",
        "Use the assets in the vault to fund new initiatives and projects that provide additional value for Lomen holders. 💡"
      ]
    },
    {
      phase: 4,
      title: "NFT Marketplace",
      status: "FUTURE",
      statusColor: "#6B7280",
      icon: "4",
      description: [
        "Create a commission-free NFT auction and marketplace for Lomen NFT holders that will allow club members to trade their NFTs without paying any commission (As long as they hold one Lomen NFT). 🎨",
        "Promote the marketplace to attract buyers and sellers, and provide tools and resources to help community members participate in the marketplace. 📢",
        "Explore partnerships with other NFT marketplaces to increase visibility and adoption, and to enable Lomen holders to trade their NFTs on multiple platforms. 🤝"
      ]
    },
    {
      phase: 5,
      title: "DAO Governance",
      status: "FUTURE",
      statusColor: "#6B7280",
      icon: "5",
      description: [
        "Set up Lomen DAO governance to give members a voice in decision-making and enable them to propose and vote on new initiatives and projects. 🗳️",
        "Implement a transparent voting system where Lomen NFT holders can participate in key decisions about the ecosystem's future. 📊",
        "Establish governance parameters including voting power based on NFT holdings, proposal submission process, and voting thresholds. ⚖️",
        "Create a treasury management system for community funds and establish clear guidelines for fund allocation and project funding. 💼"
      ]
    },
    {
      phase: 6,
      title: "Token Creation",
      status: "FUTURE",
      statusColor: "#6B7280",
      icon: "6",
      description: [
        "Develop a token creation and bonding system exclusive to Lomen NFT holders. 🪙",
        "This feature will allow verified members to create new tokens, define bonding curves, and set initial liquidity and utility parameters — all within a secure and community-governed environment. 🔐",
        "Implement smart contract templates for token creation with customizable parameters including supply, distribution, and utility functions. 📝",
        "The goal is to empower innovation within the Lomen ecosystem, enabling holders to launch and support new projects while maintaining shared value through the Lomen Vault. 📈"
      ]
    },
    {
      phase: 7,
      title: "Travel Platform",
      status: "FUTURE",
      statusColor: "#6B7280",
      icon: "7",
      description: [
        "Develop a travel comparison and booking platform integrated with crypto payments and rewards. 🌍",
        "Users will be able to search and book flights while earning crypto-based incentives, creating a real-world use case that connects the Lomen ecosystem to the broader economy. 💸",
        "All profits generated from the platform will flow into the Lomen Vault, contributing to staking rewards and future Lomen Club initiatives. 💰",
        "Implement loyalty programs and exclusive travel deals for Lomen NFT holders, creating additional utility and value for the community. ✈️"
      ]
    }
  ];

  return (
    <div style={{ minHeight: '100vh', backgroundColor: 'var(--bg-primary)' }}>
      <TopNav scrollToAbout={scrollToAbout} scrollToRoadmap={scrollToRoadmap} scrollToTeam={scrollToTeam} scrollToPartners={scrollToPartners} />
      
      {/* Hero Section - Full Height Image */}
      <section style={{ 
        minHeight: '100vh',
        display: 'flex',
        alignItems: 'center',
        background: 'var(--bg-primary)',
        position: 'relative',
        overflow: 'hidden'
      }}>
        {/* Full Height Background Image */}
        <div style={{
          position: 'absolute',
          top: 0,
          right: 0,
          bottom: 0,
          left: '50%',
          overflow: 'hidden',
          display: 'none'
        }} className="d-none d-lg-block">
          <img 
            src="/images/homepage/hero-nft-showcase.jpg" 
            alt="Lomen NFT Collection Showcase"
            style={{
              width: '100%',
              height: '100%',
              objectFit: 'cover',
              objectPosition: 'center',
              filter: 'brightness(1.05) contrast(1.05)'
            }}
            onError={(e) => {
              // Fallback if image doesn't exist yet
              e.currentTarget.style.display = 'none';
              const fallback = document.createElement('div');
              fallback.style.cssText = `
                display: flex;
                align-items: center;
                justify-content: center;
                width: 100%;
                height: 100%;
                color: var(--text-secondary);
                font-size: 1rem;
                text-align: center;
                background: var(--bg-elevated);
              `;
              fallback.innerHTML = `
                <div>
                  <div style="font-size: 1rem; margin-bottom: 24px; color: var(--text-secondary);">
                    Lomen NFT Image
                  </div>
                  <div style="font-size: 1.5rem; font-weight: 700; margin-bottom: 16px; color: var(--text-primary); background: linear-gradient(135deg, #23AF91, #F59E0B); background-clip: text; -webkit-background-clip: text; -webkit-text-fill-color: transparent;">
                    Lomen NFT Collection
                  </div>
                  <div style="font-size: 1rem; color: var(--text-secondary); max-width: 320px; margin: 0 auto; lineHeight: 1.6;">
                    Discover amazing randomly generated bot characters from our exclusive collection on KCC
                  </div>
                </div>
              `;
              if (e.currentTarget.parentNode) {
                e.currentTarget.parentNode.appendChild(fallback);
              }
            }}
          />
          {/* Gradient overlay for better text readability */}
          <div style={{
            position: 'absolute',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            background: 'linear-gradient(90deg, rgba(11, 18, 32, 0.6) 0%, rgba(11, 18, 32, 0.2) 30%, transparent 100%)',
            pointerEvents: 'none'
          }} />
        </div>

        <Container style={{ position: 'relative', zIndex: 1 }}>
          <Row>
            <Col lg={6}>
              <div style={{
                display: 'flex',
                alignItems: 'center',
                gap: '12px',
                marginBottom: '32px'
              }}>
                <div style={{
                  padding: '8px 20px',
                  background: 'rgba(35, 175, 145, 0.15)',
                  border: '1px solid rgba(35, 175, 145, 0.4)',
                  borderRadius: '24px',
                  color: '#23AF91',
                  fontSize: '0.875rem',
                  fontWeight: 700,
                  letterSpacing: '0.02em',
                  backdropFilter: 'blur(8px)'
                }}>
                  10,000 Unique NFTs on KCC
                </div>
              </div>

              <h1 style={{
                fontSize: 'clamp(2rem, 8vw, 3.5rem)',
                fontWeight: 800,
                color: 'var(--text-primary)',
                lineHeight: 1.1,
                marginBottom: '20px',
                letterSpacing: '-0.02em',
                textAlign: 'center'
              }} className="text-center">
                Welcome to <span style={{ color: '#23AF91' }}>Lomen Club</span>
              </h1>
              
              <p style={{
                fontSize: 'clamp(1rem, 4vw, 1.25rem)',
                color: 'var(--text-secondary)',
                lineHeight: 1.6,
                marginBottom: '32px',
                maxWidth: '520px',
                fontWeight: 400,
                textAlign: 'center'
              }} className="text-center mx-auto">
                As a Lomen holder, you're part of an <strong style={{ color: '#23AF91' }}>exclusive community</strong> with access to unique benefits, validator rewards, and community-driven governance.
              </p>

              <div className="d-flex flex-wrap justify-content-center align-items-center" style={{ gap: '16px', marginBottom: '40px' }}>
                <Link to="/app">
                  <Button
                    style={{
                      height: '52px',
                      padding: '0 36px',
                      background: 'linear-gradient(135deg, #23AF91 0%, #1A8C70 100%)',
                      border: 'none',
                      borderRadius: '12px',
                      fontSize: '1.125rem',
                      fontWeight: 700,
                      color: 'white',
                      transition: 'all 200ms cubic-bezier(0.4, 0, 0.2, 1)',
                      boxShadow: '0 8px 24px rgba(35, 175, 145, 0.4)'
                    }}
                    onMouseEnter={(e) => {
                      e.currentTarget.style.transform = 'translateY(-3px)';
                      e.currentTarget.style.boxShadow = '0 12px 32px rgba(35, 175, 145, 0.5)';
                    }}
                    onMouseLeave={(e) => {
                      e.currentTarget.style.transform = 'translateY(0)';
                      e.currentTarget.style.boxShadow = '0 8px 24px rgba(35, 175, 145, 0.4)';
                    }}
                  >
                    <span style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                      Launch App 
                      <ArrowRight size={22} />
                    </span>
                  </Button>
                </Link>
                
                <Button
                  variant="outline-primary"
                  onClick={scrollToAbout}
                  style={{
                    height: '52px',
                    padding: '0 28px',
                    border: '2px solid var(--border-primary)',
                    background: 'transparent',
                    borderRadius: '12px',
                    fontSize: '1.125rem',
                    fontWeight: 600,
                    color: 'var(--text-primary)',
                    transition: 'all 200ms cubic-bezier(0.4, 0, 0.2, 1)'
                  }}
                  onMouseEnter={(e) => {
                    e.currentTarget.style.backgroundColor = 'var(--bg-elevated)';
                    e.currentTarget.style.transform = 'translateY(-2px)';
                    e.currentTarget.style.borderColor = '#23AF91';
                  }}
                  onMouseLeave={(e) => {
                    e.currentTarget.style.backgroundColor = 'transparent';
                    e.currentTarget.style.transform = 'translateY(0)';
                    e.currentTarget.style.borderColor = 'var(--border-primary)';
                  }}
                >
                  Learn More
                </Button>
              </div>
            </Col>
          </Row>
        </Container>
      </section>

      {/* About Section - Detailed Content with Proper Layout */}
      <section ref={aboutRef} style={{ 
        padding: '80px 0',
        background: 'var(--bg-primary)'
      }}>
        <Container>
          <Row className="justify-content-center">
            <Col lg={10}>
              <h2 style={{
                fontSize: '2.5rem',
                fontWeight: 700,
                color: 'var(--text-primary)',
                marginBottom: '48px',
                textAlign: 'center'
              }}>
                About <span style={{ color: '#23AF91' }}>Lomen Club</span>
              </h2>
              
              {/* What is Lomen NFT? */}
              <Row className="align-items-center mb-5">
                <Col md={4}>
                  <div style={{
                    height: '300px',
                    background: 'var(--bg-elevated)',
                    borderRadius: '12px',
                    border: '1px solid var(--border-primary)',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    position: 'relative',
                    overflow: 'hidden'
                  }}>
                    <img 
                      src="/images/homepage/about-nft-showcase.jpg" 
                      alt="Lomen NFT Showcase"
                      style={{
                        width: '100%',
                        height: '100%',
                        objectFit: 'cover',
                        objectPosition: 'center'
                      }}
                      onError={(e) => {
                        e.currentTarget.style.display = 'none';
                        const fallback = document.createElement('div');
                        fallback.style.cssText = `
                          display: flex;
                          align-items: center;
                          justify-content: center;
                          width: 100%;
                          height: '100%';
                          color: var(--text-secondary);
                          font-size: 1rem;
                          text-align: center;
                        `;
                        fallback.innerHTML = `
                          <div>
                            <div style="font-size: 1rem; margin-bottom: 8px;">
                              Lomen NFT Image
                            </div>
                            <div style="font-size: 0.875rem; color: var(--text-secondary);">
                              Your Lomen NFT will appear here
                            </div>
                          </div>
                        `;
                        if (e.currentTarget.parentNode) {
                          e.currentTarget.parentNode.appendChild(fallback);
                        }
                      }}
                    />
                  </div>
                </Col>
                <Col md={8}>
                  <h3 style={{ 
                    color: 'var(--text-primary)', 
                    marginBottom: '16px',
                    fontSize: '1.5rem',
                    fontWeight: 600
                  }}>
                    What Is Lomen NFT?
                  </h3>
                  <p style={{ 
                    color: 'var(--text-secondary)',
                    lineHeight: 1.7,
                    margin: 0,
                    fontSize: '1rem'
                  }}>
                    <strong>Lomen: The First Generated Art NFTs on KCC</strong><br /><br />
                    Lomen is a collection of 10,000 randomly generated art NFTs on KCC, created by the KuCoin team.<br /><br />
                    Each Lomen has a unique look and set of features.
                  </p>
                </Col>
              </Row>

              {/* What is Lomen Club? */}
              <Row className="align-items-center mb-5">
                <Col md={8}>
                  <h3 style={{ 
                    color: 'var(--text-primary)', 
                    marginBottom: '16px',
                    fontSize: '1.5rem',
                    fontWeight: 600
                  }}>
                    What Is Lomen Club?
                  </h3>
                  <p style={{ 
                    color: 'var(--text-secondary)',
                    lineHeight: 1.7,
                    margin: 0,
                    fontSize: '1rem'
                  }}>
                    <strong>Lomen Club: A Community-Driven Initiative</strong><br /><br />
                    Lomen Club is a community-driven initiative that aims to provide value to Lomen NFT holders through various initiatives and projects.<br /><br />
                    Our goal is to create a sustainable ecosystem that benefits all Lomen holders and helps grow the Lomen community.
                  </p>
                </Col>
                <Col md={4}>
                  <div style={{
                    height: '300px',
                    background: 'var(--bg-elevated)',
                    borderRadius: '12px',
                    border: '1px solid var(--border-primary)',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    position: 'relative',
                    overflow: 'hidden'
                  }}>
                    <img 
                      src="/images/homepage/community-showcase.jpg" 
                      alt="Lomen Community Showcase"
                      style={{
                        width: '100%',
                        height: '100%',
                        objectFit: 'cover',
                        objectPosition: 'center'
                      }}
                      onError={(e) => {
                        e.currentTarget.style.display = 'none';
                        const fallback = document.createElement('div');
                        fallback.style.cssText = `
                          display: flex;
                          align-items: center;
                          justify-content: center;
                          width: 100%;
                          height: '100%';
                          color: var(--text-secondary);
                          font-size: 1rem;
                          textAlign: 'center';
                        `;
                        fallback.innerHTML = `
                          <div>
                            <div style="font-size: 1rem; margin-bottom: 8px;">
                              Community Image
                            </div>
                            <div style="font-size: 0.875rem; color: var(--text-secondary);">
                              Community showcase will appear here
                            </div>
                          </div>
                        `;
                        if (e.currentTarget.parentNode) {
                          e.currentTarget.parentNode.appendChild(fallback);
                        }
                      }}
                    />
                  </div>
                </Col>
              </Row>

              {/* KCC Validator */}
              <Row className="align-items-center mb-5">
                <Col md={4}>
                  <div style={{
                    height: '300px',
                    background: 'var(--bg-elevated)',
                    borderRadius: '12px',
                    border: '1px solid var(--border-primary)',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    position: 'relative',
                    overflow: 'hidden'
                  }}>
                    <img 
                      src="/images/homepage/validator-showcase.jpg" 
                      alt="KCC Validator Showcase"
                      style={{
                        width: '100%',
                        height: '100%',
                        objectFit: 'cover',
                        objectPosition: 'center'
                      }}
                      onError={(e) => {
                        e.currentTarget.style.display = 'none';
                        const fallback = document.createElement('div');
                        fallback.style.cssText = `
                          display: flex;
                          align-items: center;
                          justify-content: center;
                          width: 100%;
                          height: '100%';
                          color: var(--text-secondary);
                          font-size: 1rem;
                          textAlign: 'center';
                        `;
                        fallback.innerHTML = `
                          <div>
                            <div style="font-size: 1rem; margin-bottom: 8px;">
                              Validator Image
                            </div>
                            <div style="font-size: 0.875rem; color: var(--text-secondary);">
                              Validator showcase will appear here
                            </div>
                          </div>
                        `;
                        if (e.currentTarget.parentNode) {
                          e.currentTarget.parentNode.appendChild(fallback);
                        }
                      }}
                    />
                  </div>
                </Col>
                <Col md={8}>
                  <h3 style={{ 
                    color: 'var(--text-primary)', 
                    marginBottom: '16px',
                    fontSize: '1.5rem',
                    fontWeight: 600
                  }}>
                    KCC Validator
                  </h3>
                  <p style={{ 
                    color: 'var(--text-secondary)',
                    lineHeight: 1.7,
                    margin: 0,
                    fontSize: '1rem'
                  }}>
                    <strong>Lomen Club KCC Validator: Generating Value for Holders</strong><br /><br />
                    The Lomen Club KCC Validator is a key component of our ecosystem, generating income through staking rewards and validator commissions.<br /><br />
                    This income is used to fund community initiatives, provide staking rewards to Lomen holders, and support the growth of the Lomen ecosystem.
                  </p>
                </Col>
              </Row>
            </Col>
          </Row>
        </Container>
      </section>

      {/* Roadmap Section - Mobile Responsive */}
      <section ref={roadmapRef} style={{ 
        padding: '80px 0',
        background: 'var(--bg-primary)'
      }}>
        <Container>
          <Row className="justify-content-center">
            <Col lg={10}>
              <h2 style={{
                fontSize: '2.5rem',
                fontWeight: 700,
                color: 'var(--text-primary)',
                marginBottom: '48px',
                textAlign: 'center'
              }}>
                Our <span style={{ color: '#23AF91' }}>Roadmap</span>
              </h2>
              
              {/* Mobile Responsive Timeline */}
              <div style={{ position: 'relative' }}>
                {/* Vertical Timeline Line - Hidden on mobile */}
                <div style={{
                  position: 'absolute',
                  left: '24px',
                  top: '0',
                  bottom: '0',
                  width: '2px',
                  background: 'linear-gradient(180deg, #23AF91 0%, rgba(35, 175, 145, 0.3) 100%)',
                  zIndex: 1
                }} className="d-none d-md-block" />

                {roadmapPhases.map((phase) => (
                  <div key={phase.phase} style={{ 
                    display: 'flex', 
                    marginBottom: '40px',
                    position: 'relative',
                    zIndex: 2
                  }}>
                    {/* Timeline Dot - Mobile responsive */}
                    <div style={{
                      flex: '0 0 48px',
                      display: 'flex',
                      justifyContent: 'center',
                      alignItems: 'flex-start',
                      paddingTop: '8px'
                    }}>
                      <div style={{
                        width: '24px',
                        height: '24px',
                        background: phase.statusColor,
                        borderRadius: '50%',
                        border: '4px solid var(--bg-primary)',
                        boxShadow: `0 0 0 2px ${phase.statusColor}`,
                        zIndex: 3,
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        color: 'white',
                        fontWeight: 700,
                        fontSize: '0.75rem'
                      }}>
                        {phase.icon}
                      </div>
                    </div>
                    
                    {/* Phase Content */}
                    <div style={{ flex: 1, paddingLeft: '16px' }}>
                      <div style={{
                        background: 'var(--bg-elevated)',
                        border: '1px solid var(--border-primary)',
                        borderRadius: '12px',
                        padding: '24px',
                        boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
                        position: 'relative'
                      }}>
                        <div style={{
                          display: 'flex',
                          alignItems: 'center',
                          gap: '12px',
                          marginBottom: '16px',
                          flexWrap: 'wrap'
                        }}>
                          <h3 style={{
                            color: 'var(--text-primary)',
                            fontSize: '1.25rem',
                            fontWeight: 700,
                            margin: 0
                          }}>
                            {phase.title}
                          </h3>
                          <span style={{
                            background: `${phase.statusColor}15`,
                            color: phase.statusColor,
                            padding: '4px 12px',
                            borderRadius: '20px',
                            fontSize: '0.75rem',
                            fontWeight: 600
                          }}>
                            {phase.status}
                          </span>
                        </div>
                        <div style={{
                          color: 'var(--text-secondary)',
                          lineHeight: 1.6,
                          fontSize: '0.95rem'
                        }}>
                          {phase.description.map((item, idx) => (
                            <p key={idx} style={{ margin: '0 0 12px 0' }}>
                              {item}
                            </p>
                          ))}
                        </div>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </Col>
          </Row>
        </Container>
      </section>

      {/* Team Section - Full Height */}
      <section ref={teamRef} style={{ 
        minHeight: '100vh',
        display: 'flex',
        alignItems: 'center',
        background: 'var(--bg-primary)'
      }}>
        <Container>
          <Row className="justify-content-center">
            <Col lg={10}>
              <h2 style={{
                fontSize: '2.5rem',
                fontWeight: 700,
                color: 'var(--text-primary)',
                marginBottom: '48px',
                textAlign: 'center'
              }}>
                Our <span style={{ color: '#23AF91' }}>Team</span>
              </h2>
              
              <Row className="justify-content-center">
                {/* Timur Naimat */}
                <Col md={6} lg={4} className="mb-4">
                  <div style={{
                    background: 'var(--bg-elevated)',
                    border: '1px solid var(--border-primary)',
                    borderRadius: '12px',
                    padding: '24px',
                    textAlign: 'center',
                    height: '100%',
                    transition: 'all 200ms cubic-bezier(0.4, 0, 0.2, 1)'
                  }} onMouseEnter={(e) => {
                    e.currentTarget.style.transform = 'translateY(-4px)';
                    e.currentTarget.style.boxShadow = '0 8px 24px rgba(0, 0, 0, 0.15)';
                  }} onMouseLeave={(e) => {
                    e.currentTarget.style.transform = 'translateY(0)';
                    e.currentTarget.style.boxShadow = 'none';
                  }}>
                    <div style={{
                      width: '120px',
                      height: '120px',
                      borderRadius: '50%',
                      background: 'var(--bg-surface)',
                      margin: '0 auto 20px',
                      overflow: 'hidden',
                      border: '2px solid var(--border-primary)'
                    }}>
                      <img 
                        src="/images/nfts/5268.webp" 
                        alt="Timur Naimat - Lomen NFT 5268"
                        style={{
                          width: '100%',
                          height: '100%',
                          objectFit: 'cover',
                          objectPosition: 'center'
                        }}
                        onError={(e) => {
                          e.currentTarget.style.display = 'none';
                          const fallback = document.createElement('div');
                          fallback.style.cssText = `
                            display: flex;
                            align-items: center;
                            justify-content: center;
                            width: 100%;
                            height: 100%;
                            color: var(--text-secondary);
                            font-size: 0.875rem;
                            text-align: center;
                            background: var(--bg-surface);
                          `;
                          fallback.textContent = 'NFT 5268';
                          if (e.currentTarget.parentNode) {
                            e.currentTarget.parentNode.appendChild(fallback);
                          }
                        }}
                      />
                    </div>
                    <h3 style={{
                      color: 'var(--text-primary)',
                      fontSize: '1.25rem',
                      fontWeight: 700,
                      marginBottom: '8px'
                    }}>
                      Timur Naimat
                    </h3>
                    <p style={{
                      color: 'var(--text-secondary)',
                      lineHeight: 1.6,
                      marginBottom: '16px',
                      fontSize: '0.95rem'
                    }}>
                      Experienced blockchain developer and community builder with a passion for creating sustainable Web3 ecosystems.
                    </p>
                    <a
                      href="https://linkedin.com/in/timurnaimat"
                      target="_blank"
                      rel="noopener noreferrer"
                      style={{
                        display: 'inline-flex',
                        alignItems: 'center',
                        gap: '8px',
                        color: '#23AF91',
                        textDecoration: 'none',
                        fontWeight: 600,
                        fontSize: '0.875rem',
                        transition: 'all 150ms cubic-bezier(0.4, 0, 0.2, 1)'
                      }}
                      onMouseEnter={(e) => {
                        e.currentTarget.style.color = '#1A8C70';
                      }}
                      onMouseLeave={(e) => {
                        e.currentTarget.style.color = '#23AF91';
                      }}
                    >
                      LinkedIn Profile
                    </a>
                  </div>
                </Col>

                {/* Evgenia Boyankova */}
                <Col md={6} lg={4} className="mb-4">
                  <div style={{
                    background: 'var(--bg-elevated)',
                    border: '1px solid var(--border-primary)',
                    borderRadius: '12px',
                    padding: '24px',
                    textAlign: 'center',
                    height: '100%',
                    transition: 'all 200ms cubic-bezier(0.4, 0, 0.2, 1)'
                  }} onMouseEnter={(e) => {
                    e.currentTarget.style.transform = 'translateY(-4px)';
                    e.currentTarget.style.boxShadow = '0 8px 24px rgba(0, 0, 0, 0.15)';
                  }} onMouseLeave={(e) => {
                    e.currentTarget.style.transform = 'translateY(0)';
                    e.currentTarget.style.boxShadow = 'none';
                  }}>
                    <div style={{
                      width: '120px',
                      height: '120px',
                      borderRadius: '50%',
                      background: 'var(--bg-surface)',
                      margin: '0 auto 20px',
                      overflow: 'hidden',
                      border: '2px solid var(--border-primary)'
                    }}>
                      <img 
                        src="/images/nfts/5873.webp" 
                        alt="Evgenia Boyankova - Lomen NFT 5873"
                        style={{
                          width: '100%',
                          height: '100%',
                          objectFit: 'cover',
                          objectPosition: 'center'
                        }}
                        onError={(e) => {
                          e.currentTarget.style.display = 'none';
                          const fallback = document.createElement('div');
                          fallback.style.cssText = `
                            display: flex;
                            align-items: center;
                            justify-content: center;
                            width: 100%;
                            height: 100%;
                            color: var(--text-secondary);
                            font-size: 0.875rem;
                            text-align: center;
                            background: var(--bg-surface);
                          `;
                          fallback.textContent = 'NFT 5873';
                          if (e.currentTarget.parentNode) {
                            e.currentTarget.parentNode.appendChild(fallback);
                          }
                        }}
                      />
                    </div>
                    <h3 style={{
                      color: 'var(--text-primary)',
                      fontSize: '1.25rem',
                      fontWeight: 700,
                      marginBottom: '8px'
                    }}>
                      Evgenia Boyankova
                    </h3>
                    <p style={{
                      color: 'var(--text-secondary)',
                      lineHeight: 1.6,
                      marginBottom: '16px',
                      fontSize: '0.95rem'
                    }}>
                      Marketing strategist and community manager with expertise in growing Web3 communities and driving engagement.
                    </p>
                    <a
                      href="https://linkedin.com/in/evgeniaboyankova"
                      target="_blank"
                      rel="noopener noreferrer"
                      style={{
                        display: 'inline-flex',
                        alignItems: 'center',
                        gap: '8px',
                        color: '#23AF91',
                        textDecoration: 'none',
                        fontWeight: 600,
                        fontSize: '0.875rem',
                        transition: 'all 150ms cubic-bezier(0.4, 0, 0.2, 1)'
                      }}
                      onMouseEnter={(e) => {
                        e.currentTarget.style.color = '#1A8C70';
                      }}
                      onMouseLeave={(e) => {
                        e.currentTarget.style.color = '#23AF91';
                      }}
                    >
                      LinkedIn Profile
                    </a>
                  </div>
                </Col>

                {/* Bashar AlNeimat */}
                <Col md={6} lg={4} className="mb-4">
                  <div style={{
                    background: 'var(--bg-elevated)',
                    border: '1px solid var(--border-primary)',
                    borderRadius: '12px',
                    padding: '24px',
                    textAlign: 'center',
                    height: '100%',
                    transition: 'all 200ms cubic-bezier(0.4, 0, 0.2, 1)'
                  }} onMouseEnter={(e) => {
                    e.currentTarget.style.transform = 'translateY(-4px)';
                    e.currentTarget.style.boxShadow = '0 8px 24px rgba(0, 0, 0, 0.15)';
                  }} onMouseLeave={(e) => {
                    e.currentTarget.style.transform = 'translateY(0)';
                    e.currentTarget.style.boxShadow = 'none';
                  }}>
                    <div style={{
                      width: '120px',
                      height: '120px',
                      borderRadius: '50%',
                      background: 'var(--bg-surface)',
                      margin: '0 auto 20px',
                      overflow: 'hidden',
                      border: '2px solid var(--border-primary)'
                    }}>
                      <img 
                        src="/images/nfts/3751.webp" 
                        alt="Bashar AlNeimat - Lomen NFT 3751"
                        style={{
                          width: '100%',
                          height: '100%',
                          objectFit: 'cover',
                          objectPosition: 'center'
                        }}
                        onError={(e) => {
                          e.currentTarget.style.display = 'none';
                          const fallback = document.createElement('div');
                          fallback.style.cssText = `
                            display: flex;
                            align-items: center;
                            justify-content: center;
                            width: 100%;
                            height: 100%;
                            color: var(--text-secondary);
                            font-size: 0.875rem;
                            text-align: center;
                            background: var(--bg-surface);
                          `;
                          fallback.textContent = 'NFT 3751';
                          if (e.currentTarget.parentNode) {
                            e.currentTarget.parentNode.appendChild(fallback);
                          }
                        }}
                      />
                    </div>
                    <h3 style={{
                      color: 'var(--text-primary)',
                      fontSize: '1.25rem',
                      fontWeight: 700,
                      marginBottom: '8px'
                    }}>
                      Bashar AlNeimat
                    </h3>
                    <p style={{
                      color: 'var(--text-secondary)',
                      lineHeight: 1.6,
                      marginBottom: '16px',
                      fontSize: '0.95rem'
                    }}>
                      Business development specialist with extensive experience in blockchain partnerships and ecosystem growth.
                    </p>
                    <a
                      href="https://linkedin.com/in/basharalneimat"
                      target="_blank"
                      rel="noopener noreferrer"
                      style={{
                        display: 'inline-flex',
                        alignItems: 'center',
                        gap: '8px',
                        color: '#23AF91',
                        textDecoration: 'none',
                        fontWeight: 600,
                        fontSize: '0.875rem',
                        transition: 'all 150ms cubic-bezier(0.4, 0, 0.2, 1)'
                      }}
                      onMouseEnter={(e) => {
                        e.currentTarget.style.color = '#1A8C70';
                      }}
                      onMouseLeave={(e) => {
                        e.currentTarget.style.color = '#23AF91';
                      }}
                    >
                      LinkedIn Profile
                    </a>
                  </div>
                </Col>
              </Row>
            </Col>
          </Row>
        </Container>
      </section>

      {/* Partners Section */}
      <section ref={partnersRef} style={{ 
        padding: '80px 0',
        background: 'var(--bg-primary)'
      }}>
        <Container>
          <Row className="justify-content-center">
            <Col lg={10}>
              <h2 style={{
                fontSize: '2.5rem',
                fontWeight: 700,
                color: 'var(--text-primary)',
                marginBottom: '48px',
                textAlign: 'center'
              }}>
                Our <span style={{ color: '#23AF91' }}>Partners</span>
              </h2>
              
              <Row className="justify-content-center">
                <Col md={6} lg={4}>
                  <div style={{
                    background: 'var(--bg-elevated)',
                    border: '1px solid var(--border-primary)',
                    borderRadius: '12px',
                    padding: '32px',
                    textAlign: 'center',
                    transition: 'all 200ms cubic-bezier(0.4, 0, 0.2, 1)'
                  }} onMouseEnter={(e) => {
                    e.currentTarget.style.transform = 'translateY(-4px)';
                    e.currentTarget.style.boxShadow = '0 8px 24px rgba(0, 0, 0, 0.15)';
                  }} onMouseLeave={(e) => {
                    e.currentTarget.style.transform = 'translateY(0)';
                    e.currentTarget.style.boxShadow = 'none';
                  }}>
                    <div style={{
                      width: '120px',
                      height: '120px',
                      borderRadius: '12px',
                      background: 'var(--bg-surface)',
                      margin: '0 auto 20px',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      padding: '16px',
                      border: '1px solid var(--border-primary)'
                    }}>
                      <img 
                        src="/images/partners/kcc.png" 
                        alt="KuCoin Community Chain (KCC)"
                        style={{
                          width: '100%',
                          height: '100%',
                          objectFit: 'contain',
                          objectPosition: 'center'
                        }}
                        onError={(e) => {
                          e.currentTarget.style.display = 'none';
                          const fallback = document.createElement('div');
                          fallback.style.cssText = `
                            display: flex;
                            align-items: center;
                            justify-content: center;
                            width: 100%;
                            height: 100%;
                            color: var(--text-secondary);
                            font-size: 0.875rem;
                            text-align: center;
                            background: var(--bg-surface);
                          `;
                          fallback.textContent = 'KCC Logo';
                          if (e.currentTarget.parentNode) {
                            e.currentTarget.parentNode.appendChild(fallback);
                          }
                        }}
                      />
                    </div>
                    <h3 style={{
                      color: 'var(--text-primary)',
                      fontSize: '1.25rem',
                      fontWeight: 700,
                      marginBottom: '8px'
                    }}>
                      KuCoin Community Chain (KCC)
                    </h3>
                    <p style={{
                      color: 'var(--text-secondary)',
                      lineHeight: 1.6,
                      margin: 0,
                      fontSize: '0.95rem'
                    }}>
                      High-performance decentralized public chain built by KuCoin and KCS communities.
                    </p>
                  </div>
                </Col>
              </Row>
            </Col>
          </Row>
        </Container>
      </section>

      {/* Footer */}
      <Footer />
    </div>
  );
};

export default Homepage;
